packages:
  - apps/*
  - packages/*

minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
blockExoticSubdeps: true

overrides:
  miniflare>sharp: 0.35.2

allowBuilds:
  esbuild: true
  sharp: true
  supabase: true
  workerd: true

nodeVersion: 24.18.0
engineStrict: true
savePrefix: ""
