import type { EffectiveNutritionFood } from "@health-design/domain";

export const T17_BASKET_SEED_VERSION = "t17-basket-v1" as const;

export const T17_BASKET_GROUPS = [
  "protein",
  "vegetable",
  "fruit",
  "carbohydrate",
  "dairy_alternative",
  "fat",
] as const;

export const T17_PURCHASE_FORMS = [
  "dry",
  "fresh",
  "drained",
  "canned",
  "natural",
  "prepared",
  "marinated",
] as const;

export type T17BasketGroup = (typeof T17_BASKET_GROUPS)[number];
export type T17PurchaseForm = (typeof T17_PURCHASE_FORMS)[number];

export type T17BasketSeedItem = Readonly<{
  canonicalFoodKey: string;
  ediblePart: string;
  foodState: EffectiveNutritionFood["foodState"];
  group: T17BasketGroup;
  name: string;
  purchaseForm: T17PurchaseForm;
  sourceCode: string;
  sourceKey: "bedca_public" | "ciqual_2025" | "fineli" | "usda_sr_legacy";
}>;

const item = (input: T17BasketSeedItem): T17BasketSeedItem => input;

export const T17_FIXED_BASKET = [
  item({
    canonicalFoodKey: "food:ciqual-36017",
    ediblePart: "meat_without_skin",
    foodState: "raw",
    group: "protein",
    name: "Pechuga de pollo cruda",
    purchaseForm: "fresh",
    sourceCode: "36017",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-36019",
    ediblePart: "meat_without_skin",
    foodState: "raw",
    group: "protein",
    name: "Contramuslo de pollo sin piel crudo",
    purchaseForm: "fresh",
    sourceCode: "36019",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-36304",
    ediblePart: "meat",
    foodState: "raw",
    group: "protein",
    name: "Pechuga de pavo cruda",
    purchaseForm: "fresh",
    sourceCode: "36304",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-6106",
    ediblePart: "lean_meat",
    foodState: "raw",
    group: "protein",
    name: "Ternera magra cruda",
    purchaseForm: "fresh",
    sourceCode: "6106",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-28204",
    ediblePart: "meat",
    foodState: "raw",
    group: "protein",
    name: "Lomo de cerdo crudo",
    purchaseForm: "fresh",
    sourceCode: "28204",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-34001",
    ediblePart: "meat",
    foodState: "raw",
    group: "protein",
    name: "Conejo crudo",
    purchaseForm: "fresh",
    sourceCode: "34001",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-22000",
    ediblePart: "without_shell",
    foodState: "raw",
    group: "protein",
    name: "Huevo de gallina",
    purchaseForm: "fresh",
    sourceCode: "22000",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-26044",
    ediblePart: "flesh",
    foodState: "raw",
    group: "protein",
    name: "Merluza cruda",
    purchaseForm: "fresh",
    sourceCode: "26044",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-26161",
    ediblePart: "flesh",
    foodState: "raw",
    group: "protein",
    name: "Salmón crudo",
    purchaseForm: "fresh",
    sourceCode: "26161",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:fineli-804",
    ediblePart: "flesh",
    foodState: "raw",
    group: "protein",
    name: "Bacalao crudo",
    purchaseForm: "fresh",
    sourceCode: "804",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:ciqual-26039",
    ediblePart: "drained_product",
    foodState: "cooked",
    group: "protein",
    name: "Atún al natural escurrido",
    purchaseForm: "drained",
    sourceCode: "26039",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-10021",
    ediblePart: "peeled_flesh",
    foodState: "raw",
    group: "protein",
    name: "Gamba pelada cruda",
    purchaseForm: "fresh",
    sourceCode: "10021",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-10001",
    ediblePart: "flesh",
    foodState: "raw",
    group: "protein",
    name: "Calamar crudo",
    purchaseForm: "fresh",
    sourceCode: "10001",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:usda-sr-172475",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "protein",
    name: "Tofu firme natural",
    purchaseForm: "natural",
    sourceCode: "172475",
    sourceKey: "usda_sr_legacy",
  }),
  item({
    canonicalFoodKey: "food:fineli-33499",
    ediblePart: "dry_product",
    foodState: "raw",
    group: "protein",
    name: "Soja texturizada seca",
    purchaseForm: "dry",
    sourceCode: "33499",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:ciqual-25598",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "protein",
    name: "Seitán natural",
    purchaseForm: "natural",
    sourceCode: "25598",
    sourceKey: "ciqual_2025",
  }),

  item({
    canonicalFoodKey: "food:fineli-352",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Tomate",
    purchaseForm: "fresh",
    sourceCode: "352",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20034",
    ediblePart: "without_skin",
    foodState: "raw",
    group: "vegetable",
    name: "Cebolla",
    purchaseForm: "fresh",
    sourceCode: "20034",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:fineli-386",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Pimiento rojo",
    purchaseForm: "fresh",
    sourceCode: "386",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:fineli-300",
    ediblePart: "without_skin",
    foodState: "raw",
    group: "vegetable",
    name: "Zanahoria",
    purchaseForm: "fresh",
    sourceCode: "300",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20020",
    ediblePart: "flesh_and_skin",
    foodState: "raw",
    group: "vegetable",
    name: "Calabacín",
    purchaseForm: "fresh",
    sourceCode: "20020",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20053",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Berenjena",
    purchaseForm: "fresh",
    sourceCode: "20053",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20057",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Brócoli",
    purchaseForm: "fresh",
    sourceCode: "20057",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20016",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Coliflor",
    purchaseForm: "fresh",
    sourceCode: "20016",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20059",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Espinaca",
    purchaseForm: "fresh",
    sourceCode: "20059",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20171",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Lechuga romana",
    purchaseForm: "fresh",
    sourceCode: "20171",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20019",
    ediblePart: "flesh_and_skin",
    foodState: "raw",
    group: "vegetable",
    name: "Pepino",
    purchaseForm: "fresh",
    sourceCode: "20019",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20061",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Judía verde",
    purchaseForm: "fresh",
    sourceCode: "20061",
    sourceKey: "ciqual_2025",
  }),

  item({
    canonicalFoodKey: "food:ciqual-13039",
    ediblePart: "flesh_and_skin",
    foodState: "raw",
    group: "fruit",
    name: "Manzana",
    purchaseForm: "fresh",
    sourceCode: "13039",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:fineli-11049",
    ediblePart: "flesh_without_skin",
    foodState: "raw",
    group: "fruit",
    name: "Plátano",
    purchaseForm: "fresh",
    sourceCode: "11049",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:fineli-11045",
    ediblePart: "flesh_without_skin",
    foodState: "raw",
    group: "fruit",
    name: "Naranja",
    purchaseForm: "fresh",
    sourceCode: "11045",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:fineli-11046",
    ediblePart: "flesh_without_skin",
    foodState: "raw",
    group: "fruit",
    name: "Mandarina",
    purchaseForm: "fresh",
    sourceCode: "11046",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:ciqual-13037",
    ediblePart: "flesh_and_skin",
    foodState: "raw",
    group: "fruit",
    name: "Pera",
    purchaseForm: "fresh",
    sourceCode: "13037",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-13021",
    ediblePart: "flesh_without_skin",
    foodState: "raw",
    group: "fruit",
    name: "Kiwi",
    purchaseForm: "fresh",
    sourceCode: "13021",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:fineli-447",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "fruit",
    name: "Fresa",
    purchaseForm: "fresh",
    sourceCode: "447",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:fineli-477",
    ediblePart: "flesh_without_skin_and_seeds",
    foodState: "raw",
    group: "fruit",
    name: "Melón",
    purchaseForm: "fresh",
    sourceCode: "477",
    sourceKey: "fineli",
  }),

  item({
    canonicalFoodKey: "food:ciqual-9100",
    ediblePart: "dry_product",
    foodState: "raw",
    group: "carbohydrate",
    name: "Arroz blanco seco",
    purchaseForm: "dry",
    sourceCode: "9100",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-9810",
    ediblePart: "dry_product",
    foodState: "raw",
    group: "carbohydrate",
    name: "Pasta seca",
    purchaseForm: "dry",
    sourceCode: "9810",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-7110",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "carbohydrate",
    name: "Pan integral",
    purchaseForm: "prepared",
    sourceCode: "7110",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-9310",
    ediblePart: "dry_product",
    foodState: "raw",
    group: "carbohydrate",
    name: "Avena",
    purchaseForm: "dry",
    sourceCode: "9310",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-9681",
    ediblePart: "dry_product",
    foodState: "raw",
    group: "carbohydrate",
    name: "Cuscús seco",
    purchaseForm: "dry",
    sourceCode: "9681",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-9340",
    ediblePart: "dry_product",
    foodState: "raw",
    group: "carbohydrate",
    name: "Quinoa seca",
    purchaseForm: "dry",
    sourceCode: "9340",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-4008",
    ediblePart: "without_skin",
    foodState: "raw",
    group: "carbohydrate",
    name: "Patata",
    purchaseForm: "fresh",
    sourceCode: "4008",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-4101",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "carbohydrate",
    name: "Boniato",
    purchaseForm: "fresh",
    sourceCode: "4101",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20359",
    ediblePart: "dry_seed",
    foodState: "raw",
    group: "carbohydrate",
    name: "Lenteja seca",
    purchaseForm: "dry",
    sourceCode: "20359",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20516",
    ediblePart: "dry_seed",
    foodState: "raw",
    group: "carbohydrate",
    name: "Garbanzo seco",
    purchaseForm: "dry",
    sourceCode: "20516",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20525",
    ediblePart: "dry_seed",
    foodState: "raw",
    group: "carbohydrate",
    name: "Alubia seca",
    purchaseForm: "dry",
    sourceCode: "20525",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20072",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "carbohydrate",
    name: "Guisante",
    purchaseForm: "fresh",
    sourceCode: "20072",
    sourceKey: "ciqual_2025",
  }),

  item({
    canonicalFoodKey: "food:ciqual-19033",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "dairy_alternative",
    name: "Leche semidesnatada",
    purchaseForm: "natural",
    sourceCode: "19033",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:fineli-11736",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "dairy_alternative",
    name: "Yogur natural sin azúcar",
    purchaseForm: "natural",
    sourceCode: "11736",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:bedca-2507",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "dairy_alternative",
    name: "Queso fresco de Burgos",
    purchaseForm: "fresh",
    sourceCode: "2507",
    sourceKey: "bedca_public",
  }),
  item({
    canonicalFoodKey: "food:bedca-2515",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "dairy_alternative",
    name: "Queso semicurado de vaca",
    purchaseForm: "prepared",
    sourceCode: "2515",
    sourceKey: "bedca_public",
  }),
  item({
    canonicalFoodKey: "food:usda-sr-175215",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "dairy_alternative",
    name: "Bebida de soja sin azúcar enriquecida en calcio",
    purchaseForm: "natural",
    sourceCode: "175215",
    sourceKey: "usda_sr_legacy",
  }),
  item({
    canonicalFoodKey: "food:ciqual-19646",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "dairy_alternative",
    name: "Queso fresco batido natural",
    purchaseForm: "natural",
    sourceCode: "19646",
    sourceKey: "ciqual_2025",
  }),

  item({
    canonicalFoodKey: "food:ciqual-17270",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "fat",
    name: "Aceite de oliva virgen extra",
    purchaseForm: "natural",
    sourceCode: "17270",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:fineli-11057",
    ediblePart: "flesh_without_skin_and_stone",
    foodState: "raw",
    group: "fat",
    name: "Aguacate",
    purchaseForm: "fresh",
    sourceCode: "11057",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:ciqual-15000",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "fat",
    name: "Almendra natural",
    purchaseForm: "natural",
    sourceCode: "15000",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-15005",
    ediblePart: "kernel",
    foodState: "unspecified",
    group: "fat",
    name: "Nuez natural",
    purchaseForm: "natural",
    sourceCode: "15005",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-15047",
    ediblePart: "dry_seed",
    foodState: "unspecified",
    group: "fat",
    name: "Chía",
    purchaseForm: "dry",
    sourceCode: "15047",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-15034",
    ediblePart: "ground_seed",
    foodState: "unspecified",
    group: "fat",
    name: "Lino molido",
    purchaseForm: "dry",
    sourceCode: "15034",
    sourceKey: "ciqual_2025",
  }),
] as const satisfies readonly T17BasketSeedItem[];

export const T17_RESERVE_BASKET = [
  item({
    canonicalFoodKey: "food:ciqual-26034",
    ediblePart: "drained_product",
    foodState: "cooked",
    group: "protein",
    name: "Sardina en conserva escurrida",
    purchaseForm: "drained",
    sourceCode: "26034",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-26123",
    ediblePart: "drained_product",
    foodState: "cooked",
    group: "protein",
    name: "Caballa en conserva al natural escurrida",
    purchaseForm: "drained",
    sourceCode: "26123",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-10013",
    ediblePart: "whole_edible_product",
    foodState: "cooked",
    group: "protein",
    name: "Mejillón cocido sin salsa",
    purchaseForm: "prepared",
    sourceCode: "10013",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-26080",
    ediblePart: "flesh",
    foodState: "raw",
    group: "protein",
    name: "Dorada cruda",
    purchaseForm: "fresh",
    sourceCode: "26080",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-21505",
    ediblePart: "lean_meat",
    foodState: "raw",
    group: "protein",
    name: "Cordero magro crudo",
    purchaseForm: "fresh",
    sourceCode: "21505",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20917",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "protein",
    name: "Tempeh natural",
    purchaseForm: "natural",
    sourceCode: "20917",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20139",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Calabaza",
    purchaseForm: "fresh",
    sourceCode: "20139",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20067",
    ediblePart: "drained_product",
    foodState: "cooked",
    group: "vegetable",
    name: "Alcachofa al natural escurrida",
    purchaseForm: "drained",
    sourceCode: "20067",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20279",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Espárrago verde",
    purchaseForm: "fresh",
    sourceCode: "20279",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20056",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Champiñón",
    purchaseForm: "fresh",
    sourceCode: "20056",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20039",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "vegetable",
    name: "Puerro",
    purchaseForm: "fresh",
    sourceCode: "20039",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:fineli-34361",
    ediblePart: "flesh_without_skin_and_stone",
    foodState: "raw",
    group: "fruit",
    name: "Mango",
    purchaseForm: "fresh",
    sourceCode: "34361",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:ciqual-13043",
    ediblePart: "flesh_and_skin_without_stone",
    foodState: "raw",
    group: "fruit",
    name: "Melocotón",
    purchaseForm: "fresh",
    sourceCode: "13043",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-13028",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "fruit",
    name: "Arándano",
    purchaseForm: "fresh",
    sourceCode: "13028",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-13395",
    ediblePart: "whole_edible_product",
    foodState: "raw",
    group: "fruit",
    name: "Uva",
    purchaseForm: "fresh",
    sourceCode: "13395",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:fineli-11056",
    ediblePart: "flesh_without_skin",
    foodState: "raw",
    group: "fruit",
    name: "Piña",
    purchaseForm: "fresh",
    sourceCode: "11056",
    sourceKey: "fineli",
  }),
  item({
    canonicalFoodKey: "food:ciqual-9380",
    ediblePart: "dry_product",
    foodState: "raw",
    group: "carbohydrate",
    name: "Trigo sarraceno seco",
    purchaseForm: "dry",
    sourceCode: "9380",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-20066",
    ediblePart: "drained_product",
    foodState: "cooked",
    group: "carbohydrate",
    name: "Maíz dulce cocido escurrido",
    purchaseForm: "drained",
    sourceCode: "20066",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:ciqual-19865",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "dairy_alternative",
    name: "Kéfir natural",
    purchaseForm: "natural",
    sourceCode: "19865",
    sourceKey: "ciqual_2025",
  }),
  item({
    canonicalFoodKey: "food:fineli-30208",
    ediblePart: "whole_edible_product",
    foodState: "unspecified",
    group: "dairy_alternative",
    name: "Bebida de avena sin azúcar enriquecida en calcio",
    purchaseForm: "natural",
    sourceCode: "30208",
    sourceKey: "fineli",
  }),
] as const satisfies readonly T17BasketSeedItem[];

export const T17_FIXED_BASKET_KEYS = T17_FIXED_BASKET.map(
  ({ canonicalFoodKey }) => canonicalFoodKey,
);
export const T17_RESERVE_BASKET_KEYS = T17_RESERVE_BASKET.map(
  ({ canonicalFoodKey }) => canonicalFoodKey,
);
export const T17_BASKET = [...T17_FIXED_BASKET, ...T17_RESERVE_BASKET] as const;
